# Chirps

GET http://localhost:8080/api/chirps

GET http://localhost:8080/api/chirps/99

POST http://localhost:8080/api/chirps
{
  "body": "I had kerfuffle for breakfast"
}

POST http://localhost:8080/api/validate_chirp
{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

# Users

GET http://localhost:8080/api/users

GET http://localhost:8080/api/users/1

POST http://localhost:8080/api/users
{
  "email": "foobar@baz",
  "password": "secure_password"
}
